baseURL: https://datamcgraw.netlify.app/
languageCode: en-us
title: Jamie McGraw Data Science Portfolio
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: "Jamie McGraw's website for Data Science projects"
      # A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      # -- AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Jamie McGraw Data Science Portfolio
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        postcode: NW16XY
        #street: Street
        #title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jamiepatrickmcgraw@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+44) 07506644669
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Jamie Data
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: fa-twitter
      #  label: Twitter
       # url: https://www.twitter.com
    #  - icon: fa-facebook
     #   label: Facebook
      #  url: https://www.facebook.com
    #  - icon: fa-instagram
     #   label: Instagram
      #  url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/jamiemacg93/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jamie-mcgraw/
  image: ''
  name: Jamie McGraw
  navigation:
    #button1:
    #  - name: Get Started
    #    url: blogs
    #button2:
    #  - name: Log In
    #    url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
    #  - name: Generic Blog
    #   url: blogs/ipsum
    # - name: Elements
    #    url: elements.html
    menu: Menu
    subtitle: return home here
    title: Home
  tiles:
    enable: yes
    showcase:
      - image: laskowski-tri-optimal.jpg
        subtitle: Unsupervised learning analysis of the world's development indicators
        title: Grouping the world's countries
        url: blogs/country
      - image: guns.jpg
        subtitle: We found some interesting associations with mental health
        title: Data exploration - mass shootings
        url: blogs/shoot
      - image: card.jpeg
        subtitle: Let's explore when card fraud happens and to whom
        title: Data exploration - card fraud
        url: blogs/card_fraud
      - image: energy.jpg
        subtitle: Found some interesting insights about South Africa's energy crisis
        title: Energy output - South Africa focus
        url: blogs/energy
    #  - image: pic05.jpg
     #   subtitle: Ipsum Dolor Sit Amet
      #  title: Consequat
       # url: blogs/ipsum
    #  - image: pic06.jpg
     #   subtitle: Feugiat Amet Tempus
      #  title: Etiam
       # url: blogs/ipsum
 # two:
  #  buttonText: Get Started
   # enable: yes
    #subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
     # \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
    #  condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
     # pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      #Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
    #  amet pharetra et feugiat tempus."
   # title: Massa libero
    #url: blogs
